from pyrogram import Client, filters
import random
from pyrogram import *
from DAXXMUSIC import app
#---


messages = [
    "Hello {name}!",
    "Hey {name}, kaise ho?",
    "What's up {name}?",
    "Aap kaise hain, {name}?",
    "Namaste {name}!",
    "Hey {name}, kya chal raha hai?",
    "Aapka din kaisa raha, {name}?",
    "Hi {name}, sab theek hai?",
    "Kya haal hai {name}?",
    "Good day, {name}!",
    "Hello there, {name}!",
    "Greetings {name}!",
    "Nice to see you, {name}!",
    "Hey {name}, how's everything going?",
    "Hope you're doing well, {name}!",
    "Long time no see, {name}!",
    "What have you been up to, {name}?",
    "How's life treating you, {name}?",
    "How are things on your end, {name}?",
    "Hi {name}, kaisi chal rahi hai zindagi?",
    "Howdy {name}!",
    "Hey {name}, sab changa?",
    "Hi {name}, ki haal hai?",
    "What's happening, {name}?",
    "How's everything, {name}?",
    "Hey {name}, kya haal chal hai?",
    "Hi {name}, aap kaise hain?",
    "Hello {name}, kaisa diwas hai?",
    "How are you feeling today, {name}?",
    "Hello {name}, kaisa guzar raha hai din?",
    "Hey {name}, kaise lag rahe hain aap?",
    "What's new, {name}?",
    "How's your day going, {name}?",
    "Hi {name}, kaise ho aap?",
    "Hello {name}, aap kaise hain?",
    "Hey {name}, kya haal hai aapka?",
    "What's the latest, {name}?",
    "How are you today, {name}?",
    "Hello {name}, kya kar rahe hain aap?",
    "How's everything with you, {name}?",
    "Hi {name}, kya haal chal hai?",
    "Hello {name}, kaise hain aap?",
    "Hey {name}, aap kaise hain?",
    "What's going on, {name}?",
    "How are you feeling, {name}?",
    "Hi {name}, aap kaisi hain?",
    "Hello {name}, kaisi ho aap?",
    "Hey {name}, kya haal hai?",
    "How's your day been, {name}?",
    "Hi {name}, kya chal raha hai?",
    "Hello {name}, kya haal hai aapka?",
    "Hey {name}, kaise ho aap?",
    "What's up, {name}?",
    "How's your day so far, {name}?",
    "Hi {name}, kya kar rahe ho?",
    "Hello {name}, kaisi hai aap?",
    "Hey {name}, kaisi lag rahi hain aap?",
    "What's going on with you, {name}?",
    "How are you doing today, {name}?",
    "Hi {name}, aap kaisi lag rahe hain?",
    "Hello {name}, kya kar rahe ho aap?",
    "Hey {name}, kya ho raha hai?",
    "How's your day treating you, {name}?",
    "Hi {name}, kya haal chal hai aapka?",
    "Hello {name}, kya ho raha hai aaj?",
    "Hey {name}, kaise lag rahe ho?",
    "What's new with you, {name}?",
    "How's your day, {name}?",
    "Hi {name}, kaisa lag raha hai?",
    "Hello {name}, kaisi ho?",
    "Hey {name}, kya kar rahe ho aaj?",
    "How's everything been, {name}?",
    "Hi {name}, kaisa lag raha hai aaj?",
    "Hello {name}, kaisa guzra din?",
    "Hey {name}, kya chal raha hai aajkal?",
    "What's happening with you, {name}?",
    "How are you, {name}?",
    "Hi {name}, kya kar rahe ho aajkal?",
    "Hello {name}, kya haal hai aajkal?",
    "Hey {name}, kya kar rahe ho zindagi mein?",
    "How's everything going on, {name}?",
    "Hi {name}, kya chal raha hai aapke saath?",
    "Hello {name}, kya ho raha hai aapke saath?",
    "Hey {name}, kya haal hai aapke saath?",
    "What's up with {name}?",
    "How's life, {name}?",
    "Hi {name}, kya kar rahe hain aap aajkal?",
    "Hello {name}, kya ho raha hai aaj aapke zindagi mein?",
    "Hey {name}, kya kar rahe hain aap aajkal?",
    "How's your life, {name}?",
    "Hi {name}, kya chal raha hai aapke zindagi mein?",
    "Hello {name}, kya haal hai aapke zindagi mein?",
    "Hey {name}, kya kar rahe hain aap?",
    "What's going on in {name}'s life?",
    "How's {name} doing?",
    "Hi {name}, kya chal raha hai?",
    "Hello {name}, kya haal hai?",
    "Hey {name}, kya ho raha hai?",
    "What's happening, {name}?",
    "How's {name}?",
    "Hi {name}, kya kar rahe ho?",
    "Hello {name}, kya haal hai aapka?",
    "Hey {name}, kaise ho?",
    "What's up, {name}?",
    "How's it going, {name}?",
    "Hi {name}, kya kar rahe ho aajkal?",
    "Hello {name}, kya haal hai aaj aapka?",
    "Hey {name}, kya kar rahe hain aap aajkal?",
    "What's new, {name}?",
    "How are things, {name}?",
    "Hi {name}, kya chal raha hai aapke saath?",
    "Hello {name}, kya ho raha hai aapke saath?",
    "Hey {name}, kya haal hai aapke saath?",
    "What's up with {name}?",
    "How's life, {name}?",
    "Hi {name}, kya kar rahe",
    
]

# Function to handle incoming messages
@app.on_message(filters.command(["exi","exiko"], prefixes=["n", "N"]))
def start_command(client, message):
    # Extract user's first name
    name = message.from_user.mention
    # Select a random message
    random_message = random.choice(messages)
    # Replace {name} in the message with the user's first name
    reply_text = random_message.format(name=name)
    # Reply to the user with the formatted message
    message.reply_text(reply_text)
